# Generated by Django 4.2.5 on 2023-09-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='reading_time_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время чтения (минуты)'),
        ),
    ]
