# Generated by Django 4.2.5 on 2023-09-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_reading_time_minutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='image',
            new_name='main_image',
        ),
    ]
